### ISSUE TITLE
First submitted guess is ignored

### ISSUE THREAD

**Issue by nbgraham** [nbgraham/word-guessing#4]

**Comment by karsenkeith** [comment]
@nbgraham I just played a bit over lunch and I think it was working correctly for me? Repro steps?

**Comment by karsenkeith** [comment]
<img width="480" alt="Screen Shot 2022-01-20 at 11 29 51 AM" src="https://user-images.githubusercontent.com/35581427/150390859-caa786f6-fa9a-4897-9d87-b05355de5a97.png">

**Comment by nbgraham** [comment]
@karsenkeith seems to only happen when you use the "=" button on the keyboard to submit
But then the second time, it works


Actually, I couldn't reproduce reliable. Seems to only happen sometimes

**Comment by nbgraham** [comment]
I think it was bc of the form submission, but hard to know for sure bc it was intermittent
Might be cool to persist the guesses into localStorage or something so you can refresh and keep your guesses
